version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            pip install flake8
            flake8 app/
      - persist_to_workspace:
          root: .
          paths:
            - venv

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Test server startup
          command: |
            . /workspace/venv/bin/activate
            uvicorn app.main:app --host 127.0.0.1 --port 8003 &
            sleep 5
            curl -f http://127.0.0.1:8003/index

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build